-- TODO CHANGE THIS
DROP TABLE IF EXISTS squawker;
CREATE TABLE squawker (id INTEGER PRIMARY KEY AUTOINCREMENT,
                       post VARCHAR(150),
                       ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
