-- TODO change this
DROP TABLE IF EXISTS messages;
CREATE TABLE messages (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	message VARCHAR(140) DEFAULT NULL,
	createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
